def rules
  {
    destination_city: [
      {
        constraint: ->(i) { i.present? },
        message: 'sss'
      }
    ]
  }
end

def validate(subject)
  tasks = subject[:tasks].map do |hash|
    hash[:data].each do |k, v|
      rule = rules[k.to_sym]
      if rule
        messages = rule.map { |r| r[:constraint].call(v) ? nil : r[:message] }.compact
        hash[:errors].push({name: k, messages: messages}) if messages.any?
      end
    end
    hash
  end
  subject.merge('tasks' => tasks)
end

o = {:tasks=>
  [{:data=>
     {:creation_origin=>"excel",
      :is_roundtrip=>nil,
      :status=>"UNASSIGNED",
      :urgency=>"REGULAR",
      :vehicle_kind=>"SCOOTER",
      :organization_id=>1,
      :company_id=>1931,
      :notes=>"Fragile package 2",
      :source_name=>"Yahav",
      :source_city=>"תל אביב",
      :source_street=>"טיומקין",
      :source_number=>"1",
      :source_floor=>nil,
      :source_apartment=>nil,
      :source_phone=>"052-5452168",
      :source_email=>"noa@lionwheel.com",
      :source_salary=>nil,
      :destination_salary=>10000,
      :destination_city=>"Springfield",
      :destination_street=>"1st",
      :destination_number=>"34",
      :destination_floor=>"2",
      :destination_apartment=>"21",
      :destination_notes=>"code is #4567",
      :destination_recipient_name=>"David Smith",
      :destination_name=>"",
      :destination_phone=>"1234567",
      :destination_email=>"david.smith@gmail.com",
      :destination_longitude=>nil,
      :destination_latitude=>nil,
      :destination_entrance_code=>nil,
      :destination_entrance=>nil,
      :destination_zip_code=>"",
      :destination_phone2=>nil,
      :destination_eta_at=>nil,
      :destination_state=>nil,
      :task_type=>:delivery,
      :wait_time=>nil,
      :wp_order_id=>"12345",
      :wp_order_at=>nil,
      :batch_id=>"190c475f772bd6bc0df10f45",
      :extra_barcode=>nil,
      :driver_id=>"",
      :pickup_at=>"24/03/2025",
      :packages_quantity=>2,
      :surfaces_quantity=>0,
      :document_number=>nil,
      :price=>nil,
      :stop_time=>"3",
      :money_collect=>nil,
      :greeting=>nil,
      :is_self_pickup=>false,
      :gifter_phone=>"12345678",
      :gifter_name=>"John Dou",
      :external_location_id=>nil,
      :external_company_id=>nil,
      :external_company_name=>nil,
      :external_location_name=>"",
      :destination_earliest_at=>"10:00",
      :destination_latest_at=>"14:30",
      :volume=>nil,
      "חריף"=>"",
      "משימה"=>""},
    :row_num=>1,
    :errors=>[]},
   {:data=>
     {:creation_origin=>"excel",
      :is_roundtrip=>nil,
      :status=>"UNASSIGNED",
      :urgency=>"REGULAR",
      :vehicle_kind=>"SCOOTER",
      :organization_id=>1,
      :company_id=>1931,
      :notes=>"Fragile package 2",
      :source_name=>"Yahav",
      :source_city=>"תל אביב",
      :source_street=>"טיומקין",
      :source_number=>"1",
      :source_floor=>nil,
      :source_apartment=>nil,
      :source_phone=>"052-5452168",
      :source_email=>"noa@lionwheel.com",
      :source_salary=>nil,
      :destination_salary=>10000,
      :destination_city=>"",
      :destination_street=>"1st",
      :destination_number=>"34",
      :destination_floor=>"2",
      :destination_apartment=>"21",
      :destination_notes=>"code is #4567",
      :destination_recipient_name=>"David Smith",
      :destination_name=>"",
      :destination_phone=>"1234567",
      :destination_email=>"david.smith@gmail.com",
      :destination_longitude=>nil,
      :destination_latitude=>nil,
      :destination_entrance_code=>nil,
      :destination_entrance=>nil,
      :destination_zip_code=>"",
      :destination_phone2=>nil,
      :destination_eta_at=>nil,
      :destination_state=>nil,
      :task_type=>:delivery,
      :wait_time=>nil,
      :wp_order_id=>"12345",
      :wp_order_at=>nil,
      :batch_id=>"190c475f772bd6bc0df10f45",
      :extra_barcode=>nil,
      :driver_id=>"",
      :pickup_at=>"24/03/2025",
      :packages_quantity=>2,
      :surfaces_quantity=>0,
      :document_number=>nil,
      :price=>nil,
      :stop_time=>"3",
      :money_collect=>nil,
      :greeting=>nil,
      :is_self_pickup=>false,
      :gifter_phone=>"12345678",
      :gifter_name=>"John Dou",
      :external_location_id=>nil,
      :external_company_id=>nil,
      :external_company_name=>nil,
      :external_location_name=>"",
      :destination_earliest_at=>"10:00",
      :destination_latest_at=>"14:30",
      :volume=>nil,
      "חריף"=>"",
      "משימה"=>""},
    :row_num=>2,
    :errors=>[]}],
 :file=>nil,
 :same_wp_order_ids=>[],
 :urgency=>"REGULAR",
 :vehicle_kind=>"SCOOTER",
 :field_names=>
  [:row_num,
   :destination_city,
   :destination_street,
   :destination_number,
   :destination_floor,
   :destination_apartment,
   :destination_recipient_name,
   :destination_phone,
   :destination_notes,
   :destination_email,
   :is_roundtrip,
   :urgency,
   :notes,
   :wp_order_id,
   :packages_quantity,
   :price,
   :money_collect,
   :destination_phone2,
   :greeting,
   :destination_earliest_at,
   :destination_latest_at,
   :is_self_pickup,
   :gifter_phone,
   :gifter_name,
   :destination_zip_code,
   :destination_name,
   :volume,
   :destination_eta_at],
 :custom_fields=>[{:name=>"חריף", :required=>false, :type=>"enum", :custom_field_options=>["בקטנה", "בינוני", "חריף", "חריך תאילנדי"]}, {:name=>"משימה", :required=>false, :type=>"enum", :custom_field_options=>["התקנה", "מדידה"]}]}


require 'active_support/core_ext/object/blank'

result = validate(o)
puts result
