template: Hello, %s!
defaultName: Stranger
server:
  applicationConnectors:
    - type: http
      port: 8989
  adminConnectors:
    - type: http
      port: 8081
logging:
  level: INFO
  loggers:
    com.graphhopper: DEBUG 